sprite_index = asset_get_index("spr_ev_un_soldier_idle_d")
image_speed = 0
cycle = 1
e_state = (0 << 0)
e_spd = global.grid_x
e_direction = 270
e_move_x = lengthdir_x(e_spd, e_direction)
e_move_y = lengthdir_y(e_spd, e_direction)
counter = 0
e_hp = 1
e_size = (sprite_width + sprite_height)
counter = 0
player_x = 0
player_y = 0
if instance_exists(asset_get_index("obj_player"))
{
    player_x = asset_get_index("obj_player").x
    player_y = asset_get_index("obj_player").y
}
spr_idle = asset_get_index("spr_ev_un_soldier_idle_d")
spr_idle_d = asset_get_index("spr_ev_un_soldier_idle_d")
spr_idle_r = asset_get_index("spr_ev_un_soldier_idle_r")
spr_idle_u = asset_get_index("spr_ev_un_soldier_idle_u")
spr_idle_l = asset_get_index("spr_ev_un_soldier_idle_l")
spr_r = asset_get_index("spr_un_soldier_r")
spr_l = asset_get_index("spr_un_soldier_l")
spr_u = asset_get_index("spr_un_soldier_u")
spr_d = asset_get_index("spr_un_soldier_d")
set_e_direction = 3
e_path = path_add()
c_xx = x
c_yy = y
p_xx = x
p_yy = y
e_fall_sprite = asset_get_index("spr_ev_un_soldier_hit")
e_falling_sprite = asset_get_index("spr_ev_un_soldier_falling")
enemy_score = 5
playerhitme = 0
idlephase = 0
movingphase = 0
shootingphase = 0
idlecounter = 0
movingcounter = 0
shootingcounter = 0
movingnotif = 0
idlenotif = 0
previous_x = x
previous_y = y