sprite_index = asset_get_index("spr_ev_soulbadglow_particle")
image_speed = 0
draw_dust = false
counter = 0
counter_limit = irandom_range(66, 166)
is_add = irandom_range(2, 4)
y_dir = 0
t = 0
increment = 1
amplitude = irandom_range(0, 34)
xx = x
speed_up = false
y_speedup = random_range(2, 4)
dust_counter = 0
dust_limit = irandom_range(1, 128)
randomsize = irandom_range(0, 1)
control_counter = 0
control_limit = 8
control_dust = false
control_h_movement = 0
control_v_movement = 0
t_hspeed = 0
t_vspeed = 0
souleye = 0
soulfollower = 0
